# -*- coding: utf-8 -*-
"""
Created on Sat Apr  2 17:21:07 2022

@author: Andres Venialgo
"""
# CONSTANTES DEL BARRIO
FILAS_BARRIO = 100
COLUMNAS_BARRIO = 100

# CONSTANTES DE POBLACION
POBLACION_TOTAL = 1000
POLICIAS_INICIALES = 20
CRIMINALES_INICIALES = 100
CIVILES_INICIALES = POBLACION_TOTAL - \
    POLICIAS_INICIALES-CRIMINALES_INICIALES